MVCproject/Controllers/DepartmentCourseController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MVCproject.Models;
using MVCproject.ViewModels;

namespace MVCproject.Controllers
{

    public class DepartmentCourseController : Controller
    {
        AppDbContext db = new AppDbContext();
        public IActionResult Index()
        {
            return View();
        }
        [Authorize(Roles = "Instructor, Admin")]

        public IActionResult ShowCourses(int id)
        {
            Department dept = db.Departments.Include(c => c.Courses).FirstOrDefault(a => a.DeptId == id);
            return View(dept);
        }
        [Authorize(Roles = "Admin")]
        public IActionResult ManageCourses(int id)
        {
            DeptCourses model = new DeptCourses(id, db);
            return View(model);
        }
        [HttpPost]
        public IActionResult ManageCourses(int id, List<int> CoursesToRemove, List<int> CoursesToAdd)
        {
            Department dept = db.Departments.Include(d => d.Courses).FirstOrDefault(a => a.DeptId == id);
            foreach (int c in CoursesToRemove)
            {
                Course cs = db.Courses.FirstOrDefault(a => a.Id == c);
                dept.Courses.Remove(cs);
            }
            foreach (int c in CoursesToAdd)
            {
                Course cs = db.Courses.FirstOrDefault(a => a.Id == c);
                dept.Courses.Add(cs);
            }
            db.SaveChanges();
            return RedirectToAction("Index", "Department");
        }
        [Authorize(Roles = "Instructor, Admin")]
        public IActionResult SetGrade(int deptId, int crsId)
        {
            DeptCourses model = new DeptCourses(deptId, db, crsId);
            return View(model);

        }
        //manage the grades .. if thre was past grades .. display them in the input box
        [HttpPost]
        public IActionResult SetGrade(int crsId, Dictionary<int, int> degree)
        {
            foreach (var item in degree)
            {
                var searchItem = db.StudentCourses.FirstOrDefault(s => s.StudentId == item.Key && s.CourseId == crsId);
                if (searchItem == null)
                {
                    Console.WriteLine("not found grade");
                    StudentCourse sc = new StudentCourse() { CourseId = crsId, Grade = item.Value, StudentId = item.Key };
                    db.StudentCourses.Add(sc);
                    db.SaveChanges();

                }
                else
                {
                    Console.WriteLine(" found grade");
                    searchItem.Grade = item.Value;
                    db.StudentCourses.Update(searchItem);
                    db.SaveChanges();
                }
            }

            return RedirectToAction("Index", "Department");
        }
    }
}

MVCproject/Views/DepartmentCourse/ManageCourses.cshtml
@* @model Department;
 *@
 @model DeptCourses
@{
    Layout = "_Layout";
    ViewData["Title"] = "ManageCourses";
    SelectList CoursesInDept = new SelectList(Model.department.Courses, "Id", "CrsName");
    SelectList CoursesNotInDept = new SelectList(Model.CoursesNotInDept, "Id", "CrsName");
}

	<form method="post">
		<label>Choose Courses To Remove</label>

		<select class="form-select" name="CoursesToRemove" asp-items="CoursesInDept" multiple aria-label="multiple select example">
		</select>
        <label>Choose Courses To Add</label>
        <select class="form-select" name="CoursesToAdd" asp-items="CoursesNotInDept" multiple aria-label="multiple select example">
        </select>
      

        <input type="submit" value="Update" class="btn btn-info"/>
    </form>

MVCproject/Views/DepartmentCourse/SetGrade.cshtml
@model DeptCourses;
@{
    Layout = "_Layout";
    ViewData["Title"] = "SetGrade";
}

    <h1>@Model.department.DeptName department - @Model.Course.CrsName Course Grades</h1>
    <form method="post">
        @foreach(var c in Model.department.Students)
        {
            <div class="input-group mb-3">
                <span class="input-group-text" id="inputGroup-sizing-default">@c.Name</span>
                <input name="degree.@c.Id" type="text"  class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-default">
            </div>
        }
        <input value="Set Grades" type="submit" class="btn btn-primary" />
    </form>

MVCproject/Views/DepartmentCourse/ShowCourses.cshtml
@model Department;
@{
    Layout = "_Layout";
    ViewData["Title"] = "ShowCourses";
}


    <div class="d-grid gap-2 my-1">
        <h1 class="m-auto"> Department @Model.DeptName Has Courses: </h1>

    </div>
    <table class="table table-bordered table-hover">
        <thead>

            <tr>
                <td> Course Id</td>
                <td>Course Name</td>
                <td>Course Duration</td>
                <td>Grading</td>
               
            </tr>
        </thead>
        <tbody>
            @foreach (Course d in Model.Courses)
            {
                <tr>
                    <td>@d.Id</td>
                    <td>@d.CrsName</td>
                    <td>
                       @d.Duration
                    </td>
                    <td>
                        <a asp-action="SetGrade" asp-controller="DepartmentCourse" asp-route-DeptId="@Model.DeptId" class="btn btn-primary" asp-route-crsId="@d.Id">Set Grades</a>
                    </td>
                </tr>
            }
        </tbody>


    </table>